name: Test & Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.12.1

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm package

      - name: Lint
        run: pnpm lint

      - name: Astro & Svelte Check
        run: pnpm check

      - name: Test
        run: pnpm test
        env:
          VITE_PUBLIC_CLOUDINARY_CLOUD_NAME: svelte-cloudinary
